name: Chromium Notifications

on:
    push:
        branches:
            - master

jobs:
    notification:
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        runs-on: ubuntu-20.04
        name: notifications
        steps:
          - name: Run get_chromium_versions.py for ${{ github.event.ref }}
            id: get_versions
            run: |
              version=$(python get_chromium_versions.py --version ${{ github.event.ref }})
              echo "::set-output name=version::$version"

          - name: irc tag created
            uses: Gottox/irc-message-action@v2.1.3
            with:
                server: irc.libera.chat
                notice: false
                channel: "#gentoo-chromium"
                nickname: chromium-notifs-gh
                message: "New Chromium: ${{ steps.get_versions.outputs.version }}"
